Development pagination sorting swagger hw
Alexander1iubchenko/Book-store pull request #12
Opened 2023-12-02 15:22 UTC by Alexander1iubchenko

2023-12-02 18:57 UTC, RostyslavKuzmych requested changes
Overall, good. But you must analyze my comments.

2023-12-02 18:57 UTC, RostyslavKuzmych commented on src/main/java/dto/CreateBookRequestDto.java
>      private Long id;
Are you sure, that we need this field in the dto?

2023-12-02 18:57 UTC, RostyslavKuzmych commented on src/main/java/dto/CreateBookRequestDto.java
> +    @Min(0)
You use annotations of lombok, and don't use annotations from package of validation.

2023-12-02 18:57 UTC, RostyslavKuzmych commented on src/main/java/controller/BookController.java
>      public void updateBook(@PathVariable Long id, @RequestBody CreateBookRequestDto requestDto) {
Where is annotation Valid?

2023-12-02 18:57 UTC, RostyslavKuzmych commented on src/main/java/controller/BookController.java
> +    @Operation(summary = "Create a new book", description = "Creates a new book")
the same

2023-12-02 18:57 UTC, RostyslavKuzmych commented on src/main/java/dto/CreateBookRequestDto.java
> +    @NonNull
Don't use annotation NonNull and Min simultaneously

2023-12-04 08:50 UTC, bhdnchui requested changes
Just a few points to consider.

2023-12-04 08:50 UTC, bhdnchui commented on src/main/java/dto/CreateBookRequestDto.java
> +    @NotNull
Define messages for validation annotations.
For example: `@NotNull(message = "Title cannot be null.")`

2023-12-04 08:50 UTC, bhdnchui commented on src/main/java/dto/CreateBookRequestDto.java
>      private Long id;
Yeap, you can not request to create a book and define id of it. 
The server-side should create a book and define id for that book.

2023-12-04 15:51 UTC, vovasalyha approved these changes

2023-12-04 15:51 UTC, vovasalyha commented on pom.xml
> +            <groupId>jakarta.validation</groupId>
If I'm not mistaken, this dependency is fetched by the validation starter.

2023-12-04 17:33 UTC, merged