add AuthenticationService, JwtAuthenticationFilter, JwtUtil, UserLogi…
Alexander1iubchenko/Book-store pull request #16
Opened 2023-12-25 20:18 UTC by Alexander1iubchenko

…nRequestDto, UserLoginResponseDto, login endpoint to AuthController, used new filter in the SecurityFilterChain bean

2023-12-26 14:01 UTC, andrii-hoienko requested changes

2023-12-26 14:01 UTC, andrii-hoienko commented on src/main/java/controller/AuthController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto request) {
Please add @Valid annotation to apply validation rules

2023-12-26 14:01 UTC, andrii-hoienko commented on src/main/java/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
Please don`t forget about constants

2023-12-26 14:01 UTC, andrii-hoienko commented on src/main/java/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please make "Bearer " constant

2023-12-26 14:01 UTC, andrii-hoienko commented on src/main/java/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
magic number

2023-12-27 11:20 UTC, d1sam approved these changes
Well done!

2023-12-27 12:52 UTC, merged