add ShoppingCartController, AddToCartRequestDto, CartItemDto, CartIte…
Alexander1iubchenko/Book-store pull request #18
Opened 2024-01-02 23:47 UTC by Alexander1iubchenko

add ShoppingCartController, AddToCartRequestDto, CartItemDto, CartItemRequestUpdateDto, ShoppingCartDto, CartItemMapper, ShoppingCartMapper, CartItem, ShoppingCart, CartItemRepository, ShoppingCartRepository, ShoppingCartService, ShoppingCartServiceImpl,11-create-shoppingcarts-table.yaml, 12-create-cartitems-table.yaml

2024-01-03 13:38 UTC, BohdanTrue approved these changes
GJ

2024-01-03 13:38 UTC, BohdanTrue commented on src/main/java/controller/ShoppingCartController.java
> +@RequestMapping("/api/cart")
It's not necessary but you can add this property `server.servlet.context-path=/api` to application.properties and write all RequestMapping's without prefix `/api`

2024-01-03 13:38 UTC, BohdanTrue commented on src/main/java/model/Book.java
>      private boolean isDeleted = false;
In my project Hibernate create it by default, without explicit indication

![image](https://github.com/Alexander1iubchenko/Book-store/assets/94116191/18d3a495-ba8e-4e98-a82f-b535d4d22b21)

2024-01-03 13:38 UTC, BohdanTrue commented on src/main/java/service/ShoppingCartServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Can not find user by this id:"
make constants for messages

2024-01-03 13:38 UTC, BohdanTrue commented on src/main/resources/db/changelog/changes/11-create-shoppingcarts-table.yaml
> +                    nullable: false
unnecessary make nullable constraint for primaryKey
primaryKey has this (nullable) constraint by default

2024-01-03 15:08 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2024-01-03 15:08 UTC, vovasalyha commented on src/main/java/mapper/BookMapper.java
> +        return null;
Why does it always return null?

2024-01-03 15:08 UTC, vovasalyha commented on src/main/java/service/ShoppingCartService.java
> +    ShoppingCartDto updateQuantityOfBooksInShoppingCart(Long userId, Long id,
```suggestion
    ShoppingCartDto updateCartItem(Long userId, Long cartItemId,
```

2024-01-03 15:08 UTC, vovasalyha commented on src/main/java/service/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-01-04 08:22 UTC, d1sam requested changes
good job, but some minor changes still should be done :)

2024-01-04 08:22 UTC, d1sam commented on src/main/java/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-01-04 08:22 UTC, d1sam commented on src/main/java/model/ShoppingCart.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "shoppingCart")
```suggestion
    @OneToMany(mappedBy = "shoppingCart")
```

2024-01-05 08:58 UTC, d1sam approved these changes
well done!

2024-01-05 12:32 UTC, merged