Development docker
Alexander1iubchenko/Book-store pull request #21
Opened 2024-01-08 21:09 UTC by Alexander1iubchenko

2024-01-08 21:56 UTC, BolsunovaNataliia approved these changes

2024-01-08 21:56 UTC, BolsunovaNataliia commented on .env
> +MYSQLDB_USER=root
Good job! But I have few controversial issues.

2024-01-08 21:56 UTC, BolsunovaNataliia commented on docker-compose.yml
> +      mysql-db:
Does it work? Because I was getting an error that this is not a list.

2024-01-08 21:56 UTC, BolsunovaNataliia commented on src/main/resources/application.properties
>  jwt.expiration=500000000
Does it necessary so much time for authentication period? It is dangerous)

2024-01-08 22:14 UTC, BolsunovaNataliia commented on src/test/java/application/BookStoreApplicationTests.java
> -
Was it necessary? I remember the mentors said that this is not the best option.

2024-01-08 22:14 UTC, BolsunovaNataliia approved these changes

2024-01-09 07:16 UTC, yevheniisynytsia requested changes
Looks good, but it is not working. You have different varialbes' names in `.env` and `docker-compose.yml` files. Please work on this to make it work. I would like to have a screenshot with running containers in your PR.

2024-01-09 07:16 UTC, yevheniisynytsia commented on .gitignore
> +.env
either remove this line or remove `.env` file from your repo

2024-01-09 07:16 UTC, yevheniisynytsia commented on src/test/java/application/BookStoreApplicationTests.java
> -
+1, why did you remove it?

2024-01-09 07:16 UTC, yevheniisynytsia commented on docker-compose.yml
> +      mysql-db:
this should work fine. We can specify a condition when depending on some container

2024-01-19 14:49 UTC, vovasalyha requested changes
Please recheck env variable names you are using in docker-compose and attach a screen of a working project run by docler-compose.yml as @yevheniisynytsia asked.

2024-01-19 14:49 UTC, vovasalyha commented on docker-compose.yml
> +        "spring.datasource.username" : "$MYSQL_ROOT_USER",
You don't have env variable `MYSQL_ROOT_USER` in `.env`.

2024-01-24 00:06 UTC, Alexander1iubchenko commented
![Знімок екрана 2024-01-24 015502](https://github.com/Alexander1iubchenko/Book-store/assets/129409104/b9e2a14e-75f1-45af-91b7-42fc7b551046)

2024-01-24 00:06 UTC, Alexander1iubchenko commented
![Знімок екрана 2024-01-24 015428](https://github.com/Alexander1iubchenko/Book-store/assets/129409104/d579de92-846e-4eb6-817a-fd69ecef45cb)
![Знімок екрана 2024-01-24 014956](https://github.com/Alexander1iubchenko/Book-store/assets/129409104/0b79aa42-ec48-47e9-b573-274f0426fbc4)

2024-01-24 08:55 UTC, d1sam requested changes
Good job, but there are still some changes that should be done!

2024-01-24 08:55 UTC, d1sam commented on .gitignore
> +.env
still exists

2024-01-24 08:55 UTC, d1sam commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
this change is not related to this hw

2024-01-24 08:55 UTC, d1sam commented on src/main/resources/db/changelog/changes/13-create-orders-table.yaml
this change is not related to this hw

2024-01-24 08:55 UTC, d1sam commented on src/main/java/com/example/application/model/CartItem.java
this change is not related to this hw

2024-01-24 08:55 UTC, d1sam commented on docker-compose.yml
add empty line to the end of the file

2024-01-24 13:05 UTC, yevheniisynytsia approved these changes
🔥

2024-01-24 21:10 UTC, merged