Development book tests
Alexander1iubchenko/Book-store pull request #22
Opened 2024-01-12 11:04 UTC by Alexander1iubchenko

2024-01-16 06:44 UTC, yevheniisynytsia requested changes
too many changes unrelated to this homework. Please update the PR so that it is reviewable

2024-01-24 09:22 UTC, d1sam requested changes
good job, but please look at my minor comment and make one change!

2024-01-24 09:22 UTC, d1sam commented on src/test/java/com/example/application/controller/BookControllerTest.java
> +                .setIsbn(bookRequestDto.getIsbn());
you can use as expected book your `bookRequestDto` fields

2024-01-24 13:15 UTC, yevheniisynytsia approved these changes
🔥

2024-01-24 21:12 UTC, merged