readme
Alexander1iubchenko/Book-store pull request #23
Opened 2024-01-15 00:09 UTC by Alexander1iubchenko

2024-01-15 10:35 UTC, d1sam requested changes
Why do I see changes that not related to this hw?

2024-01-25 10:36 UTC, d1sam requested changes
please provide also .env.sample :)

2024-01-25 10:36 UTC, d1sam commented on README.md
> +* Create the .env file with the corresponding variables
please provide also .env.sample :)

2024-01-26 08:33 UTC, yevheniisynytsia approved these changes
approving but left a comment

2024-01-26 08:33 UTC, yevheniisynytsia commented on README.md
> +![](images/example_of_env.png)
picture is good

but let's imagine you are a team lead who was asked to look at a candidate's CV. You open his GH projects and want to run one of them. 
To run you have to write a lot of variables manually, you make some mistakes while writing and get angry because of the time you've spent. 

So in my opinion - the best variant is to have some kind of env file, but with a placeholder for the password. In this case you open the project - paste the password and simply run the project

2024-01-29 07:37 UTC, merged