add Dto level, add methods impl in repo and service, add mapper and c…
Alexander1iubchenko/Book-store pull request #6
Opened 2023-11-26 20:59 UTC by Alexander1iubchenko

…onfig, add controller and custom exception

2023-11-28 07:08 UTC, kshuryhin requested changes
Good job, but there are some points to consider. Also, consider better naming for git branches, which will be more feature-specific

2023-11-28 07:08 UTC, kshuryhin commented on src/main/java/service/BookServiceImpl.java
> +    private BookMapper bookMapper;
I do not see where the initialisation of this fields is done. Also, good candidates to be final

2023-11-28 07:08 UTC, kshuryhin commented on src/main/java/com/example/bookstore/BookStoreApplication.java
>  package com.example.bookstore;
This class should not be in this package I guess

2023-11-29 08:45 UTC, d1sam requested changes
Good job, but some critical changes should be done!

2023-11-29 08:45 UTC, d1sam commented on src/main/java/controller/BookController.java
> +    @GetMapping
```suggestion
    @PostMapping
```

2023-11-29 09:15 UTC, d1sam approved these changes
well done!

2023-11-29 14:36 UTC, merged